Slick = require('./_layout/_slick')
Modal = require('./_layout/_modal')
BackGroundAnimetion = require('./_animetion/backgroundAnimetion')
$ ->
	slick = new Slick($('.slick'),$('.slick-dots'))
	slick.init()
	bgAnimetion = new BackGroundAnimetion()
	bgAnimetion.init()
	modal = new Modal($('.modal'))
	modal.init()
